#!/usr/bin/env node
/**
 * Regenerate src/abis.ts from the Foundry build output.
 * Run `forge build` in packages/contracts first, then `pnpm gen-abis` here.
 */
import {readFileSync, writeFileSync} from "node:fs";
import {resolve, dirname} from "node:path";
import {fileURLToPath} from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../../contracts/out");

const contracts = [
    ["TestChip.sol/TestChip.json", "testChipAbi"],
    ["BlackjackTable.sol/BlackjackTable.json", "blackjackTableAbi"],
    ["MockRandomnessProvider.sol/MockRandomnessProvider.json", "mockRandomnessProviderAbi"],
    ["DrandRandomnessProvider.sol/DrandRandomnessProvider.json", "drandRandomnessProviderAbi"],
    ["TableChat.sol/TableChat.json", "tableChatAbi"],
    ["BlackjackTableV2.sol/BlackjackTableV2.json", "blackjackTableV2Abi"],
    ["TableFactory.sol/TableFactory.json", "tableFactoryAbi"],
    ["BankrollVault.sol/BankrollVault.json", "bankrollVaultAbi"],
    ["BlackjackTableV3.sol/BlackjackTableV3.json", "blackjackTableV3Abi"],
    ["InfiniteBlackjack.sol/InfiniteBlackjack.json", "infiniteBlackjackAbi"],
    ["SharedBankrollVault.sol/SharedBankrollVault.json", "sharedBankrollVaultAbi"],
];

let ts = `// AUTO-GENERATED by scripts/gen-abis.mjs — do not edit by hand.
// Source of truth: packages/contracts (forge build output).

`;
for (const [file, name] of contracts) {
    const artifact = JSON.parse(readFileSync(resolve(out, file), "utf8"));
    ts += `export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}
writeFileSync(resolve(here, "../src/abis.ts"), ts);
console.log("wrote src/abis.ts");
